sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zlib1g-dev
      - libqt4-opengl-dev
      - g++-4.8
      - python3
      - python-pip
      - python3-pip
compiler:
  - clang
env:
  - py=python2
  - py=python3
install:
  - export NUMBER_OF_PROCESSORS=4
  - export PATH=`pwd`/bin:${PATH}
  - export PYTHONPATH=`pwd`/lib:${PYTHONPATH}
  - export EIGEN_CFLAGS=-I`pwd`/../eigen
  - (cd ..; hg clone https://bitbucket.org/eigen/eigen/; cd eigen; hg update 3.3)
  - pip install pylint
  - pip3 install pylint
script:
  - ./check_memalign && $py ./configure -assert && $py ./build -nowarnings && PYTHON=$py ./run_pylint && ./run_tests

after_failure:
  - cat memalign.log
  - cat configure.log
  - cat pylint.log
  - cat build.log
  - cat testing.log
  - sleep 10
